Check if required swift is installed, if so skip download
IBM-Swift/Package-Builder pull request #126
Opened 2018-01-11 14:03 UTC by KyeMaloy97

2018-01-12 16:31 UTC, rolivieri requested changes
Hey @KyeMaloy97, it looks like we need to make a few updates before we can merge the PR. Can you review the comments I added?

2018-01-12 16:31 UTC, rolivieri commented on osx/install_swift_binaries.sh
>  # TODO: Since Xcode now includes the Swift compiler and Xcode is included in the macOS image provided
@KyeMaloy97 As part of this PR, can we remove the TODO comment from the code (see lines above)?

2018-01-12 16:31 UTC, rolivieri commented on osx/install_swift_binaries.sh
> +SWIFT_PREINSTALL_MINIMAL="$(swift --version | awk '{print $5}' | sed 's/[)(]//g' | cut -b 7-11 )"
@KyeMaloy97 I ran these commands on my macOS and got the following:
```
$ export SWIFT_PREINSTALL="$(swift --version | awk '{print $5}' | sed 's/[)(]//g' )"
$ echo $SWIFT_PREINSTALL
swiftlang-900.0.74.1

$ export SWIFT_PREINSTALL_MINIMAL="$(swift --version | awk '{print $5}' | sed 's/[)(]//g' | cut -b 7-11 )"
$ echo $SWIFT_PREINSTALL_MINIMAL
ang-9
```
Looking at the value assigned to the variables `SWIFT_PREINSTALL` and `SWIFT_PREINSTALL_MINIMAL`, it seems we need to do some tweaking to the code.

Also, note that the output from `swift --version` is a little different depending on the swift version:
```
$ swift --version
Apple Swift version 3.1 (swift-3.1.1-RELEASE)
Target: x86_64-apple-macosx10.9
```

```
 swift --version
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9
```
It looks like the part from that output that seems to be consistent across different versions of Swift is `Apple Swift version <version number>`.

2018-01-24 21:45 UTC, sandmman requested changes
@KyeMaloy97 A couple things to address:
1. I've added a few change requests around logging and style. I think we should try to keep the logging to only completed results, rather than intermediary output. If we easily could use a logging library with `--verbose` then these would be fine.
2. What do you think about extracting this logic to use for linux builds as well? Although travis macOS builds are our priority, this could be useful for running locally or in a different build environment. If we go this route, you could move the logic into [install-swift.sh](https://github.com/KyeMaloy97/Package-Builder/tree/arf.545)
3. How has this been tested? If we choose to go with # 2 above, we will need to make sure this works across the spectrum swift binaries and not just XCode release binaries (development snapshots - the dated ones, trunk snapshots, release snapshots)

2018-01-24 21:45 UTC, sandmman commented on build-package.sh
> +# else
This else statement should be re-added

2018-01-24 21:45 UTC, sandmman commented on osx/install_swift_binaries.sh
> +echo "Preinstalled: $SWIFT_PREINSTALL"
Let's remove these echo statements. I think we should reserve output for completed execution logic rather than intermediary output.

2018-01-24 21:45 UTC, sandmman commented on osx/install_swift_binaries.sh
> +  echo "Swift installed $SWIFT_PREINSTALL does not match snapshot $SNAPSHOT_TYPE."
Unless I'm mistaken, I think it should be okay to move the `brew update` and `brew install` commands into this else block.

2018-01-24 21:45 UTC, sandmman commented on osx/install_swift_binaries.sh
> +  echo "Required Swift version is already installed, skipping download... A"
Could you clean up these echo statements? There's some debugging logic  ('A', 'B') that aren't necessary.

2018-01-25 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM-Swift/Package-Builder?pullRequest=126) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM-Swift/Package-Builder?pullRequest=126) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM-Swift/Package-Builder?pullRequest=126) it.</sub>

2018-01-27 23:28 UTC, KyeMaloy97 commented
I added a new test for Travis with Xcode 9.2 set as the `osx_image` which comes with 4.0.3, and it does skip the download and the build for that took 48 seconds, as opposed to more than 5 minutes for the build which required downloads.

2018-02-05 15:41 UTC, sandmman commented
@KyeMaloy97 Any thoughts on point 2 above?

2018-02-06 16:03 UTC, KyeMaloy97 commented
@sandmman From that point, I assume you mean what if someone has Linux with swift installed and uses that script, you don't wan't it to go and get a download of Swift if the one needed is already available?

Would we maybe be looking at leveraging `swiftenv` to check all installed versions, and then make a decision to download or would we just do a simple `swift --version` and then determine whether a download has to happen? The latter would be simpler to implement but the former would be more useful.

2018-02-06 17:11 UTC, sandmman commented
@KyeMaloy97 Yeah, that's what I was thinking. For instance, you might be using Jenkins for continuous integration and have swift built into the environment, so we wouldn't need to download it again like on mac.

As far as swiftenv is concerned, we could technically use that for mac as well, but I think that's overly robust for the moment. I figured just share your `swift --version` logic with linux/mac and call it a day. Perhaps in the future swiftenv integration could be looked into when we have more bandwidth and the need arises, but for now lets keep it basic.

2018-02-12 15:11 UTC, merged